version: '3.8'

services:
  auth_app:
    container_name: auth_app
    image: auth_app:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run watch
    env_file: .env
    ports:
      - 9229:9229
    networks:
      - auth_networks
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - auth_networks
    volumes:
      - ./learn_isuct.sql:/docker-entrypoint-initdb.d/learn_isuct.sql
networks:
  auth_networks:
    driver: bridge
